import React from 'react';
// import useSWR from 'swr';
import Categories from '../components/Categories';
import Header from '../components/Header';
import OverviewStats from '../components/OverviewStats';
import { Colors } from '../components/Colors';
// import { fetcher } from '../utils/fetcher';

export default function Home() {
  // const { data, error } = useSWR('/api/stats', fetcher);
  const data = {
    metrics: {
      colors: 8,
      mediaQueries: 7,
      selectors: 203,
      selectorsByAttribute: 1,
      selectorsByClass: 113,
      selectorsById: 0,
      selectorsByPseudo: 14,
      selectorsByTag: 69,
      rules: 148,
      declarations: 274,
    },
    categories: [
      { name: '*', category: 'Unknown' },
      { prefixes: [''], name: 'after', category: 'Unknown' },
      { prefixes: [''], name: 'before', category: 'Unknown' },
      { prefixes: [''], name: 'after', category: 'Unknown' },
      { prefixes: [''], name: 'before', category: 'Unknown' },
      { name: 'html', category: 'Unknown' },
      { name: 'body', category: 'Unknown' },
      { name: 'hr', category: 'Unknown' },
      { prefixes: ['abbr'], name: 'where([title])', category: 'Variable' },
      { name: 'h1', category: 'Unknown' },
      { name: 'h2', category: 'Unknown' },
      { name: 'h3', category: 'Unknown' },
      { name: 'h4', category: 'Unknown' },
      { name: 'h5', category: 'Unknown' },
      { name: 'h6', category: 'Unknown' },
      { name: 'a', category: 'Unknown' },
      { name: 'b', category: 'Unknown' },
      { name: 'strong', category: 'Unknown' },
      { name: 'code', category: 'Unknown' },
      { name: 'kbd', category: 'Unknown' },
      { name: 'pre', category: 'Unknown' },
      { name: 'samp', category: 'Unknown' },
      { name: 'small', category: 'Unknown' },
      { name: 'sub', category: 'Unknown' },
      { name: 'sup', category: 'Unknown' },
      { name: 'sub', category: 'Unknown' },
      { name: 'sup', category: 'Unknown' },
      { name: 'table', category: 'Display' },
      { name: 'button', category: 'Unknown' },
      { name: 'input', category: 'Unknown' },
      { name: 'optgroup', category: 'Unknown' },
      { name: 'select', category: 'Unknown' },
      { name: 'textarea', category: 'Unknown' },
      { name: 'button', category: 'Unknown' },
      { name: 'select', category: 'Unknown' },
      { name: '[type=button]', category: 'Variable' },
      { name: '[type=reset]', category: 'Variable' },
      { name: '[type=submit]', category: 'Variable' },
      { name: 'button', category: 'Unknown' },
      { prefixes: [''], name: '-moz-focusring', category: 'Unknown' },
      { prefixes: [''], name: '-moz-ui-invalid', category: 'Unknown' },
      { name: 'progress', category: 'Unknown' },
      {
        prefixes: ['', ''],
        name: '-webkit-inner-spin-button',
        category: 'Unknown',
      },
      {
        prefixes: ['', ''],
        name: '-webkit-outer-spin-button',
        category: 'Unknown',
      },
      { name: '[type=search]', category: 'Variable' },
      {
        prefixes: ['', ''],
        name: '-webkit-search-decoration',
        category: 'Unknown',
      },
      {
        prefixes: ['', ''],
        name: '-webkit-file-upload-button',
        category: 'Unknown',
      },
      { name: 'summary', category: 'Unknown' },
      { name: 'blockquote', category: 'Unknown' },
      { name: 'dd', category: 'Unknown' },
      { name: 'dl', category: 'Unknown' },
      { name: 'figure', category: 'Unknown' },
      { name: 'h1', category: 'Unknown' },
      { name: 'h2', category: 'Unknown' },
      { name: 'h3', category: 'Unknown' },
      { name: 'h4', category: 'Unknown' },
      { name: 'h5', category: 'Unknown' },
      { name: 'h6', category: 'Unknown' },
      { name: 'hr', category: 'Unknown' },
      { name: 'p', category: 'Unknown' },
      { name: 'pre', category: 'Unknown' },
      { name: 'fieldset', category: 'Unknown' },
      { name: 'fieldset', category: 'Unknown' },
      { name: 'legend', category: 'Unknown' },
      { name: 'menu', category: 'Unknown' },
      { name: 'ol', category: 'Unknown' },
      { name: 'ul', category: 'Unknown' },
      { name: 'dialog', category: 'Unknown' },
      { name: 'textarea', category: 'Unknown' },
      {
        prefixes: ['input', ''],
        name: '-moz-placeholder',
        category: 'Unknown',
      },
      {
        prefixes: ['textarea', ''],
        name: '-moz-placeholder',
        category: 'Unknown',
      },
      { prefixes: ['input', ''], name: 'placeholder', category: 'Unknown' },
      { prefixes: ['textarea', ''], name: 'placeholder', category: 'Unknown' },
      { name: '[role=button]', category: 'Variable' },
      { name: 'button', category: 'Unknown' },
      { prefixes: [''], name: 'disabled', category: 'Unknown' },
      { name: 'audio', category: 'Unknown' },
      { name: 'canvas', category: 'Unknown' },
      { name: 'embed', category: 'Unknown' },
      { name: 'iframe', category: 'Unknown' },
      { name: 'img', category: 'Unknown' },
      { name: 'object', category: 'Unknown' },
      { name: 'svg', category: 'Unknown' },
      { name: 'video', category: 'Unknown' },
      { name: 'img', category: 'Unknown' },
      { name: 'video', category: 'Unknown' },
      { name: '[hidden]', category: 'Variable' },
      { name: '*', category: 'Unknown' },
      { prefixes: ['', ''], name: 'backdrop', category: 'Unknown' },
      { prefixes: [''], name: 'after', category: 'Unknown' },
      { prefixes: [''], name: 'before', category: 'Unknown' },
      { name: 'container', category: 'Unknown' },
      { category: '@media', name: '@media (min-width:640px)' },
      { category: '@media', name: '@media (min-width:768px)' },
      { category: '@media', name: '@media (min-width:1024px)' },
      { category: '@media', name: '@media (min-width:1280px)' },
      { category: '@media', name: '@media (min-width:1536px)' },
      { name: 'mx-auto', category: 'Margin' },
      { name: 'my-2', category: 'Margin' },
      { name: 'my-8', category: 'Margin' },
      { name: 'mb-2', category: 'Margin' },
      { name: 'mb-4', category: 'Margin' },
      { name: 'mb-8', category: 'Margin' },
      { name: 'mr-2', category: 'Margin' },
      { name: 'block', category: 'Display' },
      { name: 'flex', category: 'Display' },
      { name: 'inline-flex', category: 'Display' },
      { name: 'table', category: 'Display' },
      { name: 'grid', category: 'Display' },
      { name: 'hidden', category: 'Display' },
      { name: 'h-12', category: 'Size' },
      { name: 'h-16', category: 'Size' },
      { name: 'w-12', category: 'Size' },
      { name: 'w-16', category: 'Size' },
      { name: 'w-auto', category: 'Size' },
      { name: '-skew-x-12', category: 'Transform' },
      { name: '-skew-x-12', category: 'Transform' },
      { name: 'skew-x-12', category: 'Transform' },
      { name: 'skew-x-12', category: 'Transform' },
      { name: 'transform', category: 'Transform' },
      { name: 'cursor-default', category: 'Cursor' },
      { name: 'cursor-pointer', category: 'Cursor' },
      { name: 'grid-cols-3', category: 'Grid' },
      { name: 'grid-cols-5', category: 'Grid' },
      { name: 'flex-col', category: 'Flex' },
      { name: 'flex-wrap', category: 'Flex' },
      { name: 'items-end', category: 'Align Items' },
      { name: 'items-center', category: 'Align Items' },
      { name: 'justify-start', category: 'Justify Content' },
      { name: 'justify-between', category: 'Justify Content' },
      { name: 'gap-10', category: 'Gap' },
      { name: 'gap-2', category: 'Gap' },
      { name: 'gap-4', category: 'Gap' },
      { name: 'gap-5', category: 'Gap' },
      { name: 'rounded', category: 'Unknown' },
      { name: 'rounded-full', category: 'Border Radius' },
      { name: 'rounded-lg', category: 'Border Radius' },
      { name: 'rounded-md', category: 'Border Radius' },
      { name: 'border', category: 'Unknown' },
      { name: 'border-r-2', category: 'Border' },
      { name: 'border-gray-600', category: 'Border' },
      { name: 'bg-black\\/60', category: 'Background' },
      { name: 'bg-gray-100', category: 'Background' },
      { name: 'bg-gray-600', category: 'Background' },
      { name: 'bg-white', category: 'Background' },
      { name: 'p-2', category: 'Padding' },
      { name: 'p-4', category: 'Padding' },
      { name: 'p-5', category: 'Padding' },
      { name: 'px-16', category: 'Padding' },
      { name: 'px-2', category: 'Padding' },
      { name: 'px-2\\.5', category: 'Padding' },
      { name: 'px-6', category: 'Padding' },
      { name: 'px-8', category: 'Padding' },
      { name: 'py-0', category: 'Padding' },
      { name: 'py-0\\.5', category: 'Padding' },
      { name: 'py-2', category: 'Padding' },
      { name: 'py-4', category: 'Padding' },
      { name: 'pb-2', category: 'Padding' },
      { name: 'pr-2', category: 'Padding' },
      { name: 'pt-4', category: 'Padding' },
      { name: 'text-2xl', category: 'Text' },
      { name: 'text-6xl', category: 'Text' },
      { name: 'text-base', category: 'Text' },
      { name: 'text-lg', category: 'Text' },
      { name: 'text-lg', category: 'Text' },
      { name: 'text-xl', category: 'Text' },
      { name: 'text-xl', category: 'Text' },
      { name: 'font-bold', category: 'Font' },
      { name: 'font-extralight', category: 'Font' },
      { name: 'font-medium', category: 'Font' },
      { name: 'font-semibold', category: 'Font' },
      { name: 'leading-none', category: 'Line Height' },
      { name: 'tracking-tight', category: 'Letter Spacing' },
      { name: 'text-\\[\\#ff0000\\]', category: 'Text' },
      { name: 'text-gray-400', category: 'Text' },
      { name: 'text-green-500', category: 'Text' },
      { name: 'text-white', category: 'Text' },
      { name: 'shadow', category: 'Unknown' },
      { name: 'shadow', category: 'Unknown' },
      { name: 'shadow-sm', category: 'Box Shadow' },
      { name: 'shadow-sm', category: 'Box Shadow' },
      { name: 'outline-none', category: 'Outline' },
      { name: 'ring', category: 'Unknown' },
      { name: 'ring', category: 'Unknown' },
      { name: 'ring-2', category: 'Ring' },
      { name: 'ring-2', category: 'Ring' },
      { name: 'ring-offset-2', category: 'Ring' },
      { name: 'ring-offset-current', category: 'Ring' },
      { name: 'filter', category: 'Unknown' },
      { name: 'transition', category: 'Unknown' },
      { name: 'transition-colors', category: 'Animation' },
      { name: 'transition-shadow', category: 'Animation' },
      { name: 'duration-500', category: 'Animation' },
      { name: 'ease-in-out', category: 'Animation' },
      {
        prefixes: ['hover\\', 'shadow-md'],
        name: 'hover',
        category: 'Unknown',
      },
      {
        prefixes: ['focus\\', 'outline-none'],
        name: 'focus',
        category: 'Unknown',
      },
      { prefixes: ['focus\\', 'ring-2'], name: 'focus', category: 'Unknown' },
      {
        prefixes: ['group', 'hover .group-hover\\'],
        name: 'bg-black\\/80',
        category: 'Background',
      },
    ],
  };
  const error = false;

  return (
    <div className="container mx-auto px-4">
      <Header />
      <main className='px-4'>
        {error && (
          <p className="text-[#ff0000]">Error Loading data. Try again.</p>
        )}
        {!data && <p className="text-green-500">Loading data. Please wait.</p>}
        {!error && data && (
          <>
            <OverviewStats data={data.metrics} />
            <Colors data={data.categories} />
            <Categories data={data.categories} />
          </>
        )}
      </main>
    </div>
  );
}
